export const Menucategories = [
  "Appetizers",
  "Main Course",
  "Desserts",
  "Beverages",
  "Salads",
  "Sides",
  "Soups",
  "Sandwiches",
  "Pasta",
  "Pizza",
  "Seafood",
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Breakfast",
  "Brunch",
  "Snacks",
  "Specials",
  "Kids Menu",
  "Healthy Options",
  "Seasonal",
  "Limited Time Offer",
];
